DROP TABLE IF EXISTS Product;

CREATE TABLE Product (
   id           INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
   description  VARCHAR(61) NOT NULL
);

INSERT INTO Product(id,description) VALUES (1,'Oréos 2X');
INSERT INTO Product(id,description) VALUES (2,'Škoda 3Tr');
INSERT INTO Product(id,description) VALUES (3,'Oréos 4X');
INSERT INTO Product(id,description) VALUES (4,'Škoda 6Tr');
INSERT INTO Product(id,description) VALUES (5,'Škoda 7Tr');
INSERT INTO Product(id,description) VALUES (6,'Škoda 8Tr');
INSERT INTO Product(id,description) VALUES (7,'Škoda 9Tr');
INSERT INTO Product(id,description) VALUES (8,'Ashok Leyland 12M');
INSERT INTO Product(id,description) VALUES (9,'Škoda 14Tr');
INSERT INTO Product(id,description) VALUES (10,'Škoda 15Tr');
INSERT INTO Product(id,description) VALUES (11,'Škoda 17Tr');
INSERT INTO Product(id,description) VALUES (12,'Škoda 21Ab');
INSERT INTO Product(id,description) VALUES (13,'Škoda 21Tr');
INSERT INTO Product(id,description) VALUES (14,'Škoda 22Tr');
INSERT INTO Product(id,description) VALUES (15,'MAN 24.3x0');
INSERT INTO Product(id,description) VALUES (16,'Škoda 24Tr Irisbus');
INSERT INTO Product(id,description) VALUES (17,'Škoda 25Tr Irisbus');
INSERT INTO Product(id,description) VALUES (18,'Škoda 26Tr Solaris');
INSERT INTO Product(id,description) VALUES (19,'Škoda 27Tr Solaris');
INSERT INTO Product(id,description) VALUES (20,'Škoda 28Tr Solaris');
INSERT INTO Product(id,description) VALUES (21,'Ikarus 30');
INSERT INTO Product(id,description) VALUES (22,'Škoda 30Tr SOR');
INSERT INTO Product(id,description) VALUES (23,'Ikarus 31');
INSERT INTO Product(id,description) VALUES (24,'Škoda 31Tr SOR');
INSERT INTO Product(id,description) VALUES (25,'Škoda 32Tr SOR');
INSERT INTO Product(id,description) VALUES (26,'Škoda 33Tr SOR');
INSERT INTO Product(id,description) VALUES (27,'Škoda 35Tr');
INSERT INTO Product(id,description) VALUES (28,'Ikarus 55');
INSERT INTO Product(id,description) VALUES (29,'Ikarus 60');
INSERT INTO Product(id,description) VALUES (30,'Ikarus 66');
INSERT INTO Product(id,description) VALUES (31,'Tatra 86');
INSERT INTO Product(id,description) VALUES (32,'МАЗ-103');
INSERT INTO Product(id,description) VALUES (33,'МАЗ-104');
INSERT INTO Product(id,description) VALUES (34,'МАЗ-105');
INSERT INTO Product(id,description) VALUES (35,'МАЗ-107');
INSERT INTO Product(id,description) VALUES (36,'Iveco UA 130');
INSERT INTO Product(id,description) VALUES (37,'МАЗ-152');
INSERT INTO Product(id,description) VALUES (38,'Ikarus 180');
INSERT INTO Product(id,description) VALUES (39,'MAZ-203');
INSERT INTO Product(id,description) VALUES (40,'МАЗ-205 (автобус)');
INSERT INTO Product(id,description) VALUES (41,'МАЗ-206');
INSERT INTO Product(id,description) VALUES (42,'Ikarus 250');
INSERT INTO Product(id,description) VALUES (43,'МАЗ-251');
INSERT INTO Product(id,description) VALUES (44,'МАЗ-256');
INSERT INTO Product(id,description) VALUES (45,'Ikarus 260');
INSERT INTO Product(id,description) VALUES (46,'Ikarus 280');
INSERT INTO Product(id,description) VALUES (47,'Crown-Ikarus 286');
INSERT INTO Product(id,description) VALUES (48,'Fiat 306');
INSERT INTO Product(id,description) VALUES (49,'Fiat 308');
INSERT INTO Product(id,description) VALUES (50,'Fiat 309');
INSERT INTO Product(id,description) VALUES (51,'Ikarus 311');
INSERT INTO Product(id,description) VALUES (52,'Custom Bus');
INSERT INTO Product(id,description) VALUES (53,'Fiat 320');
INSERT INTO Product(id,description) VALUES (54,'Fiat 341 A');
INSERT INTO Product(id,description) VALUES (55,'Fiat 343');
INSERT INTO Product(id,description) VALUES (56,'Ikarus 350');
INSERT INTO Product(id,description) VALUES (57,'Iveco 370');
INSERT INTO Product(id,description) VALUES (58,'Tatra 400');
INSERT INTO Product(id,description) VALUES (59,'FAP 403 RHD');
INSERT INTO Product(id,description) VALUES (60,'Ikarus 405');
INSERT INTO Product(id,description) VALUES (61,'Ikarus 411');
INSERT INTO Product(id,description) VALUES (62,'Ikarus 412');
INSERT INTO Product(id,description) VALUES (63,'Ikarus 415');
INSERT INTO Product(id,description) VALUES (64,'Ikarus 417');
INSERT INTO Product(id,description) VALUES (65,'Fiat 418');
INSERT INTO Product(id,description) VALUES (66,'Duple 425');
INSERT INTO Product(id,description) VALUES (67,'Alfa Romeo 430A');
INSERT INTO Product(id,description) VALUES (68,'Ikarus 435');
INSERT INTO Product(id,description) VALUES (69,'Fiat 470');
INSERT INTO Product(id,description) VALUES (70,'Ikarus 480');
INSERT INTO Product(id,description) VALUES (71,'Ikarus 481');
INSERT INTO Product(id,description) VALUES (72,'Ikarus 489 Polaris');
INSERT INTO Product(id,description) VALUES (73,'Custom Bus');
INSERT INTO Product(id,description) VALUES (74,'Custom Bus');
INSERT INTO Product(id,description) VALUES (75,'Ikarus 556');
INSERT INTO Product(id,description) VALUES (76,'Fiat 642RN');
INSERT INTO Product(id,description) VALUES (77,'Fiat 666RN');
INSERT INTO Product(id,description) VALUES (78,'PAZ-672');
INSERT INTO Product(id,description) VALUES (79,'Fiat 672');
INSERT INTO Product(id,description) VALUES (80,'Fiat 680RN');
INSERT INTO Product(id,description) VALUES (81,'Fiat 682RN');
INSERT INTO Product(id,description) VALUES (82,'LAZ-695');
INSERT INTO Product(id,description) VALUES (83,'Škoda 706 RO');
INSERT INTO Product(id,description) VALUES (84,'Škoda 706 RTO');
INSERT INTO Product(id,description) VALUES (85,'Škoda 706 RTO-K');
INSERT INTO Product(id,description) VALUES (86,'Alfa Romeo 900A');
INSERT INTO Product(id,description) VALUES (87,'Oasa 901');
INSERT INTO Product(id,description) VALUES (88,'Oasa 901');
INSERT INTO Product(id,description) VALUES (89,'Alfa Romeo 902A');
INSERT INTO Product(id,description) VALUES (90,'Oasa 903');
INSERT INTO Product(id,description) VALUES (91,'Tata 1510/1512');
INSERT INTO Product(id,description) VALUES (92,'Berkhof 2000NL');
INSERT INTO Product(id,description) VALUES (93,'RAF-2203');
INSERT INTO Product(id,description) VALUES (94,'Cobus 2400');
INSERT INTO Product(id,description) VALUES (95,'Cobus 2700');
INSERT INTO Product(id,description) VALUES (96,'Cobus 3000');
INSERT INTO Product(id,description) VALUES (97,'International 3000');
INSERT INTO Product(id,description) VALUES (98,'International 3300');
INSERT INTO Product(id,description) VALUES (99,'International 3800');
INSERT INTO Product(id,description) VALUES (100,'International 3900');
INSERT INTO Product(id,description) VALUES (101,'Volvo 7700');
INSERT INTO Product(id,description) VALUES (102,'Volvo 7900');
INSERT INTO Product(id,description) VALUES (103,'Volvo 8500');
INSERT INTO Product(id,description) VALUES (104,'Volvo 8700');
INSERT INTO Product(id,description) VALUES (105,'Volvo 8900');
INSERT INTO Product(id,description) VALUES (106,'Volvo 9700');
INSERT INTO Product(id,description) VALUES (107,'Volvo 9900');
INSERT INTO Product(id,description) VALUES (108,'CDX');
INSERT INTO Product(id,description) VALUES (109,'MDX');
INSERT INTO Product(id,description) VALUES (110,'RDX');
INSERT INTO Product(id,description) VALUES (111,'LX');
INSERT INTO Product(id,description) VALUES (112,'Stelvio');
INSERT INTO Product(id,description) VALUES (113,'Humvee C-Series');
INSERT INTO Product(id,description) VALUES (114,'e-tron');
INSERT INTO Product(id,description) VALUES (115,'Q2');
INSERT INTO Product(id,description) VALUES (116,'Q3');
INSERT INTO Product(id,description) VALUES (117,'Q5');
INSERT INTO Product(id,description) VALUES (118,'Q7');
INSERT INTO Product(id,description) VALUES (119,'Q8');
INSERT INTO Product(id,description) VALUES (120,'Yusheng 007');
INSERT INTO Product(id,description) VALUES (121,'BJ20');
INSERT INTO Product(id,description) VALUES (122,'BJ40');
INSERT INTO Product(id,description) VALUES (123,'BJ40L/Plus');
INSERT INTO Product(id,description) VALUES (124,'BJ80');
INSERT INTO Product(id,description) VALUES (125,'BJ90');
INSERT INTO Product(id,description) VALUES (126,'Bentayga');
INSERT INTO Product(id,description) VALUES (127,'X1');
INSERT INTO Product(id,description) VALUES (128,'X2');
INSERT INTO Product(id,description) VALUES (129,'X3');
INSERT INTO Product(id,description) VALUES (130,'X4');
INSERT INTO Product(id,description) VALUES (131,'X5');
INSERT INTO Product(id,description) VALUES (132,'X6');
INSERT INTO Product(id,description) VALUES (133,'X7');
INSERT INTO Product(id,description) VALUES (134,'X5 M');
INSERT INTO Product(id,description) VALUES (135,'X6 M');
INSERT INTO Product(id,description) VALUES (136,'BX5');
INSERT INTO Product(id,description) VALUES (137,'BX7');
INSERT INTO Product(id,description) VALUES (138,'FRV Cross');
INSERT INTO Product(id,description) VALUES (139,'V3');
INSERT INTO Product(id,description) VALUES (140,'V5');
INSERT INTO Product(id,description) VALUES (141,'Encore');
INSERT INTO Product(id,description) VALUES (142,'Enclave');
INSERT INTO Product(id,description) VALUES (143,'Envision');
INSERT INTO Product(id,description) VALUES (144,'Song');
INSERT INTO Product(id,description) VALUES (145,'Tang');
INSERT INTO Product(id,description) VALUES (146,'Yuan');
INSERT INTO Product(id,description) VALUES (147,'Escalade');
INSERT INTO Product(id,description) VALUES (148,'Escalade ESV');
INSERT INTO Product(id,description) VALUES (149,'XT4');
INSERT INTO Product(id,description) VALUES (150,'XT5');
INSERT INTO Product(id,description) VALUES (151,'XT6');
INSERT INTO Product(id,description) VALUES (152,'CX70');
INSERT INTO Product(id,description) VALUES (153,'CS15');
INSERT INTO Product(id,description) VALUES (154,'CS35');
INSERT INTO Product(id,description) VALUES (155,'CS75');
INSERT INTO Product(id,description) VALUES (156,'CS95');
INSERT INTO Product(id,description) VALUES (157,'Q25');
INSERT INTO Product(id,description) VALUES (158,'Q35');
INSERT INTO Product(id,description) VALUES (159,'Tiggo');
INSERT INTO Product(id,description) VALUES (160,'Tiggo 3');
INSERT INTO Product(id,description) VALUES (161,'Tiggo 3X');
INSERT INTO Product(id,description) VALUES (162,'Tiggo 5 / Grand Tiggo');
INSERT INTO Product(id,description) VALUES (163,'Tiggo 7');
INSERT INTO Product(id,description) VALUES (164,'Trax');
INSERT INTO Product(id,description) VALUES (165,'Niva');
INSERT INTO Product(id,description) VALUES (166,'Tracker');
INSERT INTO Product(id,description) VALUES (167,'Captiva');
INSERT INTO Product(id,description) VALUES (168,'Captiva Sport');
INSERT INTO Product(id,description) VALUES (169,'Equinox');
INSERT INTO Product(id,description) VALUES (170,'Blazer');
INSERT INTO Product(id,description) VALUES (171,'Trailblazer');
INSERT INTO Product(id,description) VALUES (172,'Traverse');
INSERT INTO Product(id,description) VALUES (173,'Tahoe');
INSERT INTO Product(id,description) VALUES (174,'Suburban');
INSERT INTO Product(id,description) VALUES (175,'C3 Aircross');
INSERT INTO Product(id,description) VALUES (176,'C3-XR');
INSERT INTO Product(id,description) VALUES (177,'C4 Aircross');
INSERT INTO Product(id,description) VALUES (178,'C5 Aircross');
INSERT INTO Product(id,description) VALUES (179,'Knight XV');
INSERT INTO Product(id,description) VALUES (180,'Sandero Stepway');
INSERT INTO Product(id,description) VALUES (181,'Duster');
INSERT INTO Product(id,description) VALUES (182,'Winstorm');
INSERT INTO Product(id,description) VALUES (183,'Winstorm MaXX');
INSERT INTO Product(id,description) VALUES (184,'Terios');
INSERT INTO Product(id,description) VALUES (185,'Journey');
INSERT INTO Product(id,description) VALUES (186,'Durango');
INSERT INTO Product(id,description) VALUES (187,'Fengdu MX6');
INSERT INTO Product(id,description) VALUES (188,'Fengshen AX3');
INSERT INTO Product(id,description) VALUES (189,'Fengshen AX5');
INSERT INTO Product(id,description) VALUES (190,'Fengshen AX7');
INSERT INTO Product(id,description) VALUES (191,'3 Crossback');
INSERT INTO Product(id,description) VALUES (192,'DS 7 Crossback');
INSERT INTO Product(id,description) VALUES (193,'Artemis');
INSERT INTO Product(id,description) VALUES (194,'Besturn X40');
INSERT INTO Product(id,description) VALUES (195,'Besturn X80');
INSERT INTO Product(id,description) VALUES (196,'Junpai D60');
INSERT INTO Product(id,description) VALUES (197,'500X');
INSERT INTO Product(id,description) VALUES (198,'Panda 4x4');
INSERT INTO Product(id,description) VALUES (199,'Freemont');
INSERT INTO Product(id,description) VALUES (200,'Explorer');
INSERT INTO Product(id,description) VALUES (201,'Landfort');
INSERT INTO Product(id,description) VALUES (202,'One');
INSERT INTO Product(id,description) VALUES (203,'EcoSport');
INSERT INTO Product(id,description) VALUES (204,'Kuga');
INSERT INTO Product(id,description) VALUES (205,'Edge');
INSERT INTO Product(id,description) VALUES (206,'Escape');
INSERT INTO Product(id,description) VALUES (207,'Everest');
INSERT INTO Product(id,description) VALUES (208,'Explorer');
INSERT INTO Product(id,description) VALUES (209,'Flex');
INSERT INTO Product(id,description) VALUES (210,'Expedition');
INSERT INTO Product(id,description) VALUES (211,'Expedition EL');
INSERT INTO Product(id,description) VALUES (212,'Puma');
INSERT INTO Product(id,description) VALUES (213,'Sauvana');
INSERT INTO Product(id,description) VALUES (214,'Sport Chassis');
INSERT INTO Product(id,description) VALUES (215,'GM HydroGen4');
INSERT INTO Product(id,description) VALUES (216,'Terrain');
INSERT INTO Product(id,description) VALUES (217,'Acadia');
INSERT INTO Product(id,description) VALUES (218,'Yukon');
INSERT INTO Product(id,description) VALUES (219,'Yukon XL');
INSERT INTO Product(id,description) VALUES (220,'GS1');
INSERT INTO Product(id,description) VALUES (221,'New Jetstar');
INSERT INTO Product(id,description) VALUES (222,'Aoosed G5');
INSERT INTO Product(id,description) VALUES (223,'Haval H3');
INSERT INTO Product(id,description) VALUES (224,'Haval H5');
INSERT INTO Product(id,description) VALUES (225,'Haval H6');
INSERT INTO Product(id,description) VALUES (226,'H6');
INSERT INTO Product(id,description) VALUES (227,'H6 Coupe');
INSERT INTO Product(id,description) VALUES (228,'Santa Fe');
INSERT INTO Product(id,description) VALUES (229,'Boliger');
INSERT INTO Product(id,description) VALUES (230,'Trax');
INSERT INTO Product(id,description) VALUES (231,'Captiva');
INSERT INTO Product(id,description) VALUES (232,'Colorado 7');
INSERT INTO Product(id,description) VALUES (233,'Equinox');
INSERT INTO Product(id,description) VALUES (234,'Acadia');
INSERT INTO Product(id,description) VALUES (235,'BR-V');
INSERT INTO Product(id,description) VALUES (236,'Vezel');
INSERT INTO Product(id,description) VALUES (237,'CR-V');
INSERT INTO Product(id,description) VALUES (238,'Pilot');
INSERT INTO Product(id,description) VALUES (239,'Ridgeline');
INSERT INTO Product(id,description) VALUES (240,'Crosstour');
INSERT INTO Product(id,description) VALUES (241,'XR-V');
INSERT INTO Product(id,description) VALUES (242,'HR-V');
INSERT INTO Product(id,description) VALUES (243,'S2');
INSERT INTO Product(id,description) VALUES (244,'S3');
INSERT INTO Product(id,description) VALUES (245,'S6');
INSERT INTO Product(id,description) VALUES (246,'Creta/ix25');
INSERT INTO Product(id,description) VALUES (247,'Kona');
INSERT INTO Product(id,description) VALUES (248,'Nexo');
INSERT INTO Product(id,description) VALUES (249,'Santa Fe');
INSERT INTO Product(id,description) VALUES (250,'Palisade');
INSERT INTO Product(id,description) VALUES (251,'Tucson');
INSERT INTO Product(id,description) VALUES (252,'Venue');
INSERT INTO Product(id,description) VALUES (253,'EX / QX50');
INSERT INTO Product(id,description) VALUES (254,'ESQ');
INSERT INTO Product(id,description) VALUES (255,'FX / QX70');
INSERT INTO Product(id,description) VALUES (256,'JX / QX60');
INSERT INTO Product(id,description) VALUES (257,'QX / QX80');
INSERT INTO Product(id,description) VALUES (258,'MU-X');
INSERT INTO Product(id,description) VALUES (259,'S5');
INSERT INTO Product(id,description) VALUES (260,'E-Pace');
INSERT INTO Product(id,description) VALUES (261,'F-Pace');
INSERT INTO Product(id,description) VALUES (262,'I-Pace');
INSERT INTO Product(id,description) VALUES (263,'Renegade');
INSERT INTO Product(id,description) VALUES (264,'Compass');
INSERT INTO Product(id,description) VALUES (265,'Wrangler/ Wrangler 2 door');
INSERT INTO Product(id,description) VALUES (266,'Wrangler Unlimited/Wrangler 4 door');
INSERT INTO Product(id,description) VALUES (267,'Grand Cherokee');
INSERT INTO Product(id,description) VALUES (268,'Grand Commander');
INSERT INTO Product(id,description) VALUES (269,'S30');
INSERT INTO Product(id,description) VALUES (270,'Borrego/Mohave');
INSERT INTO Product(id,description) VALUES (271,'KX3');
INSERT INTO Product(id,description) VALUES (272,'Niro');
INSERT INTO Product(id,description) VALUES (273,'Seltos');
INSERT INTO Product(id,description) VALUES (274,'Sorento');
INSERT INTO Product(id,description) VALUES (275,'Sportage');
INSERT INTO Product(id,description) VALUES (276,'Telluride');
INSERT INTO Product(id,description) VALUES (277,'Niva');
INSERT INTO Product(id,description) VALUES (278,'Xray');
INSERT INTO Product(id,description) VALUES (279,'Urus');
INSERT INTO Product(id,description) VALUES (280,'Defender');
INSERT INTO Product(id,description) VALUES (281,'Range Rover Evoque');
INSERT INTO Product(id,description) VALUES (282,'Freelander');
INSERT INTO Product(id,description) VALUES (283,'Discovery Sport');
INSERT INTO Product(id,description) VALUES (284,'Discovery');
INSERT INTO Product(id,description) VALUES (285,'Range Rover Sport');
INSERT INTO Product(id,description) VALUES (286,'Range Rover');
INSERT INTO Product(id,description) VALUES (287,'X6');
INSERT INTO Product(id,description) VALUES (288,'X7');
INSERT INTO Product(id,description) VALUES (289,'GX');
INSERT INTO Product(id,description) VALUES (290,'LX');
INSERT INTO Product(id,description) VALUES (291,'NX');
INSERT INTO Product(id,description) VALUES (292,'RX');
INSERT INTO Product(id,description) VALUES (293,'UX');
INSERT INTO Product(id,description) VALUES (294,'X60');
INSERT INTO Product(id,description) VALUES (295,'X50');
INSERT INTO Product(id,description) VALUES (296,'MKC');
INSERT INTO Product(id,description) VALUES (297,'Aviator');
INSERT INTO Product(id,description) VALUES (298,'Corsair');
INSERT INTO Product(id,description) VALUES (299,'Nautilus');
INSERT INTO Product(id,description) VALUES (300,'MKT');
INSERT INTO Product(id,description) VALUES (301,'Navigator');
INSERT INTO Product(id,description) VALUES (302,'Navigator L');
INSERT INTO Product(id,description) VALUES (303,'Thar');
INSERT INTO Product(id,description) VALUES (304,'Bolero');
INSERT INTO Product(id,description) VALUES (305,'XUV500');
INSERT INTO Product(id,description) VALUES (306,'Scorpio');
INSERT INTO Product(id,description) VALUES (307,'Levante');
INSERT INTO Product(id,description) VALUES (308,'CX-3');
INSERT INTO Product(id,description) VALUES (309,'CX-30');
INSERT INTO Product(id,description) VALUES (310,'CX-4');
INSERT INTO Product(id,description) VALUES (311,'CX-5');
INSERT INTO Product(id,description) VALUES (312,'CX-8');
INSERT INTO Product(id,description) VALUES (313,'CX-9');
INSERT INTO Product(id,description) VALUES (314,'MX-30');
INSERT INTO Product(id,description) VALUES (315,'G-Class');
INSERT INTO Product(id,description) VALUES (316,'GLA-Class');
INSERT INTO Product(id,description) VALUES (317,'GLB-Class');
INSERT INTO Product(id,description) VALUES (318,'GLC-Class');
INSERT INTO Product(id,description) VALUES (319,'GLE-Class');
INSERT INTO Product(id,description) VALUES (320,'GLE-Class Coupe');
INSERT INTO Product(id,description) VALUES (321,'GLS-Class');
INSERT INTO Product(id,description) VALUES (322,'ZS');
INSERT INTO Product(id,description) VALUES (323,'GS');
INSERT INTO Product(id,description) VALUES (324,'Countryman');
INSERT INTO Product(id,description) VALUES (325,'ASX');
INSERT INTO Product(id,description) VALUES (326,'Eclipse Cross');
INSERT INTO Product(id,description) VALUES (327,'Outlander');
INSERT INTO Product(id,description) VALUES (328,'Outlander PHEV');
INSERT INTO Product(id,description) VALUES (329,'Pajero');
INSERT INTO Product(id,description) VALUES (330,'X33');
INSERT INTO Product(id,description) VALUES (331,'Armada');
INSERT INTO Product(id,description) VALUES (332,'Juke');
INSERT INTO Product(id,description) VALUES (333,'Murano');
INSERT INTO Product(id,description) VALUES (334,'Pathfinder');
INSERT INTO Product(id,description) VALUES (335,'Patrol Y61');
INSERT INTO Product(id,description) VALUES (336,'Patrol Y62');
INSERT INTO Product(id,description) VALUES (337,'Qashqai');
INSERT INTO Product(id,description) VALUES (338,'Rogue');
INSERT INTO Product(id,description) VALUES (339,'Skyline Crossover');
INSERT INTO Product(id,description) VALUES (340,'Terrano');
INSERT INTO Product(id,description) VALUES (341,'Paladin');
INSERT INTO Product(id,description) VALUES (342,'Xterra');
INSERT INTO Product(id,description) VALUES (343,'X-Trail');
INSERT INTO Product(id,description) VALUES (344,'Antara');
INSERT INTO Product(id,description) VALUES (345,'Crossland X');
INSERT INTO Product(id,description) VALUES (346,'Mokka X');
INSERT INTO Product(id,description) VALUES (347,'Nautica');
INSERT INTO Product(id,description) VALUES (348,'2008');
INSERT INTO Product(id,description) VALUES (349,'3008');
INSERT INTO Product(id,description) VALUES (350,'4008');
INSERT INTO Product(id,description) VALUES (351,'508 RXH');
INSERT INTO Product(id,description) VALUES (352,'SUV');
INSERT INTO Product(id,description) VALUES (353,'SUT');
INSERT INTO Product(id,description) VALUES (354,'Macan');
INSERT INTO Product(id,description) VALUES (355,'Cayenne');
INSERT INTO Product(id,description) VALUES (356,'Premier RiO');
INSERT INTO Product(id,description) VALUES (357,'Pronto');
INSERT INTO Product(id,description) VALUES (358,'3 City SUV');
INSERT INTO Product(id,description) VALUES (359,'Captur');
INSERT INTO Product(id,description) VALUES (360,'Kadjar');
INSERT INTO Product(id,description) VALUES (361,'Koleos');
INSERT INTO Product(id,description) VALUES (362,'Sandero Stepway');
INSERT INTO Product(id,description) VALUES (363,'Triber');
INSERT INTO Product(id,description) VALUES (364,'QM5');
INSERT INTO Product(id,description) VALUES (365,'QM3');
INSERT INTO Product(id,description) VALUES (366,'W5');
INSERT INTO Product(id,description) VALUES (367,'Cullinan');
INSERT INTO Product(id,description) VALUES (368,'Dakara');
INSERT INTO Product(id,description) VALUES (369,'Arona');
INSERT INTO Product(id,description) VALUES (370,'Ateca');
INSERT INTO Product(id,description) VALUES (371,'Tarraco');
INSERT INTO Product(id,description) VALUES (372,'Kodiaq');
INSERT INTO Product(id,description) VALUES (373,'Yeti');
INSERT INTO Product(id,description) VALUES (374,'DX7 Bolang');
INSERT INTO Product(id,description) VALUES (375,'V Cross');
INSERT INTO Product(id,description) VALUES (376,'Grand Cherokee');
INSERT INTO Product(id,description) VALUES (377,'Korando');
INSERT INTO Product(id,description) VALUES (378,'Kyron');
INSERT INTO Product(id,description) VALUES (379,'Rexton');
INSERT INTO Product(id,description) VALUES (380,'Tivoli');
INSERT INTO Product(id,description) VALUES (381,'XLV');
INSERT INTO Product(id,description) VALUES (382,'Actyon Sports');
INSERT INTO Product(id,description) VALUES (383,'Shuanghuan SCEO');
INSERT INTO Product(id,description) VALUES (384,'Ascent');
INSERT INTO Product(id,description) VALUES (385,'Crosstrek');
INSERT INTO Product(id,description) VALUES (386,'Exiga Crossover 7');
INSERT INTO Product(id,description) VALUES (387,'Forester');
INSERT INTO Product(id,description) VALUES (388,'Outback');
INSERT INTO Product(id,description) VALUES (389,'SX4');
INSERT INTO Product(id,description) VALUES (390,'Jimny');
INSERT INTO Product(id,description) VALUES (391,'Vitara');
INSERT INTO Product(id,description) VALUES (392,'Tager');
INSERT INTO Product(id,description) VALUES (393,'Tiggo');
INSERT INTO Product(id,description) VALUES (394,'Sumo');
INSERT INTO Product(id,description) VALUES (395,'Sumo Grande');
INSERT INTO Product(id,description) VALUES (396,'Aria');
INSERT INTO Product(id,description) VALUES (397,'Nexon');
INSERT INTO Product(id,description) VALUES (398,'Harrier');
INSERT INTO Product(id,description) VALUES (399,'Safari');
INSERT INTO Product(id,description) VALUES (400,'Model X');
INSERT INTO Product(id,description) VALUES (401,'Model Y');
INSERT INTO Product(id,description) VALUES (402,'C-HR');
INSERT INTO Product(id,description) VALUES (403,'RAV4');
INSERT INTO Product(id,description) VALUES (404,'Land Cruiser Wagon 3-Door');
INSERT INTO Product(id,description) VALUES (405,'Rush');
INSERT INTO Product(id,description) VALUES (406,'Land Cruiser Wagon 4-Door');
INSERT INTO Product(id,description) VALUES (407,'4Runner');
INSERT INTO Product(id,description) VALUES (408,'Fortuner');
INSERT INTO Product(id,description) VALUES (409,'Highlander');
INSERT INTO Product(id,description) VALUES (410,'Harrier');
INSERT INTO Product(id,description) VALUES (411,'Land Cruiser Prado 5-Door');
INSERT INTO Product(id,description) VALUES (412,'Land Cruiser');
INSERT INTO Product(id,description) VALUES (413,'Sequoia');
INSERT INTO Product(id,description) VALUES (414,'T4');
INSERT INTO Product(id,description) VALUES (415,'GS3');
INSERT INTO Product(id,description) VALUES (416,'GS4');
INSERT INTO Product(id,description) VALUES (417,'GS8');
INSERT INTO Product(id,description) VALUES (418,'Patriot');
INSERT INTO Product(id,description) VALUES (419,'Mokka');
INSERT INTO Product(id,description) VALUES (420,'T70');
INSERT INTO Product(id,description) VALUES (421,'SA2.0');
INSERT INTO Product(id,description) VALUES (422,'V8');
INSERT INTO Product(id,description) VALUES (423,'Atlas');
INSERT INTO Product(id,description) VALUES (424,'T-Roc');
INSERT INTO Product(id,description) VALUES (425,'Tiguan');
INSERT INTO Product(id,description) VALUES (426,'Touareg');
INSERT INTO Product(id,description) VALUES (427,'XC40');
INSERT INTO Product(id,description) VALUES (428,'XC60');
INSERT INTO Product(id,description) VALUES (429,'XC90');
INSERT INTO Product(id,description) VALUES (430,'1E');
INSERT INTO Product(id,description) VALUES (431,'2008');
INSERT INTO Product(id,description) VALUES (432,'Damai X5');
INSERT INTO Product(id,description) VALUES (433,'SR7');
INSERT INTO Product(id,description) VALUES (434,'C3 Urban Ark');
INSERT INTO Product(id,description) VALUES (435,'Landmark');
INSERT INTO Product(id,description) VALUES (436,'Deskjet');
INSERT INTO Product(id,description) VALUES (437,'DeskJet (original)');
INSERT INTO Product(id,description) VALUES (438,'DeskJet Plus');
INSERT INTO Product(id,description) VALUES (439,'DeskJet Portable');
INSERT INTO Product(id,description) VALUES (440,'Deskjet 200cci');
INSERT INTO Product(id,description) VALUES (441,'DeskJet 300j');
INSERT INTO Product(id,description) VALUES (442,'Deskjet 310 / 310 with Sheetfeeder');
INSERT INTO Product(id,description) VALUES (443,'Deskjet 320 / 320 with Sheetfeeder');
INSERT INTO Product(id,description) VALUES (444,'Deskjet 340 / 340cbi / 340 cm / 340cv');
INSERT INTO Product(id,description) VALUES (445,'Deskjet 350c / 350cbi');
INSERT INTO Product(id,description) VALUES (446,'Deskjet 400 / 400L');
INSERT INTO Product(id,description) VALUES (447,'Deskjet 420 / 420c');
INSERT INTO Product(id,description) VALUES (448,'Deskjet 450cbi / 450vci / 450wbt');
INSERT INTO Product(id,description) VALUES (449,'Deskjet 460c');
INSERT INTO Product(id,description) VALUES (450,'Deskjet 460cb');
INSERT INTO Product(id,description) VALUES (451,'Deskjet 460wf');
INSERT INTO Product(id,description) VALUES (452,'Deskjet 460wbt');
INSERT INTO Product(id,description) VALUES (453,'Deskjet 500 / 500c / 500k');
INSERT INTO Product(id,description) VALUES (454,'Deskjet 505d / 505k');
INSERT INTO Product(id,description) VALUES (455,'Deskjet 510');
INSERT INTO Product(id,description) VALUES (456,'Deskjet 520');
INSERT INTO Product(id,description) VALUES (457,'DeskJet 525q');
INSERT INTO Product(id,description) VALUES (458,'Deskjet 540');
INSERT INTO Product(id,description) VALUES (459,'Deskjet 550c');
INSERT INTO Product(id,description) VALUES (460,'Deskjet 560c / 560j / 560k');
INSERT INTO Product(id,description) VALUES (461,'Deskjet 600 / 600c / 600k');
INSERT INTO Product(id,description) VALUES (462,'Deskjet 610c / 610cl');
INSERT INTO Product(id,description) VALUES (463,'Deskjet 612c');
INSERT INTO Product(id,description) VALUES (464,'Deskjet 630c');
INSERT INTO Product(id,description) VALUES (465,'Deskjet 632c');
INSERT INTO Product(id,description) VALUES (466,'Deskjet 640c / 640u');
INSERT INTO Product(id,description) VALUES (467,'Deskjet 642c');
INSERT INTO Product(id,description) VALUES (468,'Deskjet 648c');
INSERT INTO Product(id,description) VALUES (469,'Deskjet 656c / 656cvr');
INSERT INTO Product(id,description) VALUES (470,'Deskjet 660c / 660cse / 660k');
INSERT INTO Product(id,description) VALUES (471,'Deskjet 670c / 670k / 670tv');
INSERT INTO Product(id,description) VALUES (472,'Deskjet 672c');
INSERT INTO Product(id,description) VALUES (473,'Deskjet 680c');
INSERT INTO Product(id,description) VALUES (474,'Deskjet 682c');
INSERT INTO Product(id,description) VALUES (475,'Deskjet 690c');
INSERT INTO Product(id,description) VALUES (476,'Deskjet 692c / 692k');
INSERT INTO Product(id,description) VALUES (477,'Deskjet 693c');
INSERT INTO Product(id,description) VALUES (478,'Deskjet 694c');
INSERT INTO Product(id,description) VALUES (479,'Deskjet 695c / 695cci');
INSERT INTO Product(id,description) VALUES (480,'Deskjet 697c');
INSERT INTO Product(id,description) VALUES (481,'Deskjet 710c');
INSERT INTO Product(id,description) VALUES (482,'Deskjet 712c');
INSERT INTO Product(id,description) VALUES (483,'Deskjet 720c');
INSERT INTO Product(id,description) VALUES (484,'Deskjet 722c');
INSERT INTO Product(id,description) VALUES (485,'Deskjet 810c');
INSERT INTO Product(id,description) VALUES (486,'Deskjet 812c');
INSERT INTO Product(id,description) VALUES (487,'Deskjet 815c');
INSERT INTO Product(id,description) VALUES (488,'Deskjet 820cse / 820cxi');
INSERT INTO Product(id,description) VALUES (489,'Deskjet 825c / 825cvr');
INSERT INTO Product(id,description) VALUES (490,'Deskjet 830c');
INSERT INTO Product(id,description) VALUES (491,'Deskjet 832c');
INSERT INTO Product(id,description) VALUES (492,'Deskjet 840c');
INSERT INTO Product(id,description) VALUES (493,'Deskjet 841c');
INSERT INTO Product(id,description) VALUES (494,'Deskjet 842c');
INSERT INTO Product(id,description) VALUES (495,'Deskjet 843c / 843cxe');
INSERT INTO Product(id,description) VALUES (496,'Deskjet 845c / 845cv / 845cvr');
INSERT INTO Product(id,description) VALUES (497,'Deskjet 850c / 850k');
INSERT INTO Product(id,description) VALUES (498,'Deskjet 855c / 855cse / 855cxi');
INSERT INTO Product(id,description) VALUES (499,'Deskjet 870cse / 870cxi / 870k');
INSERT INTO Product(id,description) VALUES (500,'Deskjet 880c');
INSERT INTO Product(id,description) VALUES (501,'Deskjet 882c');
INSERT INTO Product(id,description) VALUES (502,'Deskjet 890c / 890cse');
INSERT INTO Product(id,description) VALUES (503,'Deskjet 895cse / 895cxi');
INSERT INTO Product(id,description) VALUES (504,'Deskjet 916c');
INSERT INTO Product(id,description) VALUES (505,'Deskjet 920c / 920cvr / 920cxi');
INSERT INTO Product(id,description) VALUES (506,'Deskjet 930c / 930 cm');
INSERT INTO Product(id,description) VALUES (507,'Deskjet 932c');
INSERT INTO Product(id,description) VALUES (508,'Deskjet 934c');
INSERT INTO Product(id,description) VALUES (509,'Deskjet 935c');
INSERT INTO Product(id,description) VALUES (510,'Deskjet 940c / 940cvr / 940cw / 940cxi');
INSERT INTO Product(id,description) VALUES (511,'Deskjet 948c');
INSERT INTO Product(id,description) VALUES (512,'Deskjet 950c');
INSERT INTO Product(id,description) VALUES (513,'Deskjet 952c');
INSERT INTO Product(id,description) VALUES (514,'Deskjet 955c');
INSERT INTO Product(id,description) VALUES (515,'Deskjet 957c');
INSERT INTO Product(id,description) VALUES (516,'Deskjet 959c');
INSERT INTO Product(id,description) VALUES (517,'Deskjet 960c / 960cse / 960cxi');
INSERT INTO Product(id,description) VALUES (518,'Deskjet 970cse / 970cxi');
INSERT INTO Product(id,description) VALUES (519,'Deskjet 980cxi');
INSERT INTO Product(id,description) VALUES (520,'Deskjet 990 cm / 990cse/ 990cxi');
INSERT INTO Product(id,description) VALUES (521,'Deskjet 995c / 995ck');
INSERT INTO Product(id,description) VALUES (522,'Deskjet 1000 / 1000cse / 1000cxi');
INSERT INTO Product(id,description) VALUES (523,'Deskjet 1100c');
INSERT INTO Product(id,description) VALUES (524,'Deskjet 1120c / 1120cse / 1120cxi');
INSERT INTO Product(id,description) VALUES (525,'Deskjet 1125c');
INSERT INTO Product(id,description) VALUES (526,'Deskjet 1180c');
INSERT INTO Product(id,description) VALUES (527,'Deskjet 1200c / 1200c/PS');
INSERT INTO Product(id,description) VALUES (528,'Deskjet 1220c / 1220c/PS / 1220cse / 1220cxi');
INSERT INTO Product(id,description) VALUES (529,'Deskjet 1280');
INSERT INTO Product(id,description) VALUES (530,'Deskjet 1600c / 1600 cm / 1600cn');
INSERT INTO Product(id,description) VALUES (531,'Deskjet 3000 Printer');
INSERT INTO Product(id,description) VALUES (532,'Deskjet 3050A Printer All-in-One');
INSERT INTO Product(id,description) VALUES (533,'Deskjet 3320 / 3322 / 3323 3325');
INSERT INTO Product(id,description) VALUES (534,'Deskjet 3420 / 3425 / 3450');
INSERT INTO Product(id,description) VALUES (535,'Deskjet 3520 / 3535 / 3550');
INSERT INTO Product(id,description) VALUES (536,'Deskjet 3620 / 3645 / 3648 / 3650 / 3653');
INSERT INTO Product(id,description) VALUES (537,'Deskjet 3740 / 3743 / 3744 / 3745 / 3747 / 3748');
INSERT INTO Product(id,description) VALUES (538,'Deskjet 3810 / 3816 / 3820 / 3822 / 3843 / 3845 / 3847 / 3848');
INSERT INTO Product(id,description) VALUES (539,'Deskjet 3910 / 3915 / 3918 / 3920 / 3930 / 3938 / 3940');
INSERT INTO Product(id,description) VALUES (540,'Deskjet 5145 / 5150 / 5155 / 5160');
INSERT INTO Product(id,description) VALUES (541,'Deskjet 5420v / 5440 / 5442 / 5443');
INSERT INTO Product(id,description) VALUES (542,'Deskjet 5550 / 5551 / 5552');
INSERT INTO Product(id,description) VALUES (543,'Deskjet 5650 / 5650w / 5652 / 5655');
INSERT INTO Product(id,description) VALUES (544,'Deskjet 5740 / 5743 / 5745 / 5748');
INSERT INTO Product(id,description) VALUES (545,'Deskjet 5850');
INSERT INTO Product(id,description) VALUES (546,'Deskjet 5940 / 5943');
INSERT INTO Product(id,description) VALUES (547,'Deskjet 6122 / 6127');
INSERT INTO Product(id,description) VALUES (548,'Deskjet 6520 / 6540 / 6543 / 6548');
INSERT INTO Product(id,description) VALUES (549,'Deskjet 6620');
INSERT INTO Product(id,description) VALUES (550,'Deskjet 6830v /6840 / 6843 / 6848');
INSERT INTO Product(id,description) VALUES (551,'Deskjet 6940 / 6980');
INSERT INTO Product(id,description) VALUES (552,'Deskjet 6988');
INSERT INTO Product(id,description) VALUES (553,'Deskjet 6988dt');
INSERT INTO Product(id,description) VALUES (554,'Deskjet 9300');
INSERT INTO Product(id,description) VALUES (555,'Deskjet 9650 / 9670 / 9680');
INSERT INTO Product(id,description) VALUES (556,'Deskjet 9800 / 9800d');
INSERT INTO Product(id,description) VALUES (557,'Deskjet D1455');
INSERT INTO Product(id,description) VALUES (558,'Deskjet D1520');
INSERT INTO Product(id,description) VALUES (559,'Deskjet D1560');
INSERT INTO Product(id,description) VALUES (560,'Deskjet D1660');
INSERT INTO Product(id,description) VALUES (561,'Deskjet D2400');
INSERT INTO Product(id,description) VALUES (562,'Deskjet D2430');
INSERT INTO Product(id,description) VALUES (563,'Deskjet D2460');
INSERT INTO Product(id,description) VALUES (564,'Deskjet D2530');
INSERT INTO Product(id,description) VALUES (565,'Deskjet D2545');
INSERT INTO Product(id,description) VALUES (566,'Deskjet D2560');
INSERT INTO Product(id,description) VALUES (567,'Deskjet D2660');
INSERT INTO Product(id,description) VALUES (568,'Deskjet D3650');
INSERT INTO Product(id,description) VALUES (569,'Deskjet D4160');
INSERT INTO Product(id,description) VALUES (570,'Deskjet D4260');
INSERT INTO Product(id,description) VALUES (571,'DeskJet F380 All-in-One');
INSERT INTO Product(id,description) VALUES (572,'DeskJet F4100 series All-in-One');
INSERT INTO Product(id,description) VALUES (573,'Deskjet All-in-one F4185');
INSERT INTO Product(id,description) VALUES (574,'DeskJet F4200 series All-in-One');
INSERT INTO Product(id,description) VALUES (575,'DeskJet F4500 series All-in-One');
INSERT INTO Product(id,description) VALUES (576,'HP SureSupply');
INSERT INTO Product(id,description) VALUES (577,'Officejet [2]');
INSERT INTO Product(id,description) VALUES (578,'Officejet (original)');
INSERT INTO Product(id,description) VALUES (579,'Officejet 300');
INSERT INTO Product(id,description) VALUES (580,'Officejet 330');
INSERT INTO Product(id,description) VALUES (581,'Officejet 350');
INSERT INTO Product(id,description) VALUES (582,'Officejet 500 series');
INSERT INTO Product(id,description) VALUES (583,'Officejet 600');
INSERT INTO Product(id,description) VALUES (584,'Officejet 610');
INSERT INTO Product(id,description) VALUES (585,'Officejet 630');
INSERT INTO Product(id,description) VALUES (586,'Officejet 635');
INSERT INTO Product(id,description) VALUES (587,'Officejet 700');
INSERT INTO Product(id,description) VALUES (588,'Officejet 710');
INSERT INTO Product(id,description) VALUES (589,'Officejet 720');
INSERT INTO Product(id,description) VALUES (590,'Officejet 725');
INSERT INTO Product(id,description) VALUES (591,'Officejet 600 series');
INSERT INTO Product(id,description) VALUES (592,'Officejet 700 series');
INSERT INTO Product(id,description) VALUES (593,'Officejet 4110');
INSERT INTO Product(id,description) VALUES (594,'Officejet 4215');
INSERT INTO Product(id,description) VALUES (595,'Officejet 4315');
INSERT INTO Product(id,description) VALUES (596,'Officejet 4500');
INSERT INTO Product(id,description) VALUES (597,'Officejet 5110');
INSERT INTO Product(id,description) VALUES (598,'Officejet 5510');
INSERT INTO Product(id,description) VALUES (599,'Officejet 5610');
INSERT INTO Product(id,description) VALUES (600,'Officejet 6110');
INSERT INTO Product(id,description) VALUES (601,'Officejet 6210');
INSERT INTO Product(id,description) VALUES (602,'Officejet 6310');
INSERT INTO Product(id,description) VALUES (603,'Officejet 6600 e-All-in-One Printer series-H711');
INSERT INTO Product(id,description) VALUES (604,'Officejet 7110');
INSERT INTO Product(id,description) VALUES (605,'Officejet 7115');
INSERT INTO Product(id,description) VALUES (606,'Officejet 7130');
INSERT INTO Product(id,description) VALUES (607,'Officejet 7135');
INSERT INTO Product(id,description) VALUES (608,'Officejet 7140');
INSERT INTO Product(id,description) VALUES (609,'Officejet 7210');
INSERT INTO Product(id,description) VALUES (610,'Officejet 7310');
INSERT INTO Product(id,description) VALUES (611,'Officejet 7410');
INSERT INTO Product(id,description) VALUES (612,'Officejet 9110');
INSERT INTO Product(id,description) VALUES (613,'Officejet 9120');
INSERT INTO Product(id,description) VALUES (614,'Officejet 9130');
INSERT INTO Product(id,description) VALUES (615,'Officejet d125xi');
INSERT INTO Product(id,description) VALUES (616,'Officejet d135 / d135xi');
INSERT INTO Product(id,description) VALUES (617,'Officejet d145');
INSERT INTO Product(id,description) VALUES (618,'Officejet d155xi');
INSERT INTO Product(id,description) VALUES (619,'Officejet g55 / g55xi');
INSERT INTO Product(id,description) VALUES (620,'Officejet g85 / g85xi');
INSERT INTO Product(id,description) VALUES (621,'Officejet g95');
INSERT INTO Product(id,description) VALUES (622,'Officejet J5700 series');
INSERT INTO Product(id,description) VALUES (623,'Officejet k60 / k60xi');
INSERT INTO Product(id,description) VALUES (624,'Officejet k80 / k80xi');
INSERT INTO Product(id,description) VALUES (625,'Officejet L7500 series');
INSERT INTO Product(id,description) VALUES (626,'Officejet L7600 series');
INSERT INTO Product(id,description) VALUES (627,'Officejet L7700 series');
INSERT INTO Product(id,description) VALUES (628,'Officejet r40 / r40xi');
INSERT INTO Product(id,description) VALUES (629,'Officejet r45');
INSERT INTO Product(id,description) VALUES (630,'Officejet r60');
INSERT INTO Product(id,description) VALUES (631,'Officejet r65');
INSERT INTO Product(id,description) VALUES (632,'Officejet r80 / r80xi');
INSERT INTO Product(id,description) VALUES (633,'Officejet t45 / t45xi');
INSERT INTO Product(id,description) VALUES (634,'Officejet t65 / t65xi');
INSERT INTO Product(id,description) VALUES (635,'Officejet t85');
INSERT INTO Product(id,description) VALUES (636,'Officejet v30');
INSERT INTO Product(id,description) VALUES (637,'Officejet v40 / v40xi');
INSERT INTO Product(id,description) VALUES (638,'Officejet v45');
INSERT INTO Product(id,description) VALUES (639,'Officejet Pro 1150c / 1150cse');
INSERT INTO Product(id,description) VALUES (640,'Officejet Pro 1170c / 1170cse / 1170cxi');
INSERT INTO Product(id,description) VALUES (641,'Officejet Pro 1175c / 1175cse / 1175cxi');
INSERT INTO Product(id,description) VALUES (642,'Officejet Pro 8500');
INSERT INTO Product(id,description) VALUES (643,'Officejet Pro 8500 wireless');
INSERT INTO Product(id,description) VALUES (644,'Officejet Pro 8500 premier');
INSERT INTO Product(id,description) VALUES (645,'Officejet Pro 8600');
INSERT INTO Product(id,description) VALUES (646,'Officejet Pro 8600 Plus');
INSERT INTO Product(id,description) VALUES (647,'Officejet Pro 8600 Premium');
INSERT INTO Product(id,description) VALUES (648,'PSC');
INSERT INTO Product(id,description) VALUES (649,'PSC 300');
INSERT INTO Product(id,description) VALUES (650,'PSC 500 / 500xi');
INSERT INTO Product(id,description) VALUES (651,'PSC 720');
INSERT INTO Product(id,description) VALUES (652,'PSC 750 / 750xi');
INSERT INTO Product(id,description) VALUES (653,'PSC 760');
INSERT INTO Product(id,description) VALUES (654,'PSC 950 / 950xi');
INSERT INTO Product(id,description) VALUES (655,'PSC 1110');
INSERT INTO Product(id,description) VALUES (656,'PSC 1210');
INSERT INTO Product(id,description) VALUES (657,'PSC 1213');
INSERT INTO Product(id,description) VALUES (658,'PSC 1215');
INSERT INTO Product(id,description) VALUES (659,'PSC 1310');
INSERT INTO Product(id,description) VALUES (660,'PSC 1315');
INSERT INTO Product(id,description) VALUES (661,'PSC 1350');
INSERT INTO Product(id,description) VALUES (662,'PSC 1410');
INSERT INTO Product(id,description) VALUES (663,'PSC 1510');
INSERT INTO Product(id,description) VALUES (664,'PSC 1610');
INSERT INTO Product(id,description) VALUES (665,'PSC 2110 / 2110v / 2110xi');
INSERT INTO Product(id,description) VALUES (666,'PSC 2175');
INSERT INTO Product(id,description) VALUES (667,'PSC 2210 / 2210v / 2210xi');
INSERT INTO Product(id,description) VALUES (668,'PSC 2355');
INSERT INTO Product(id,description) VALUES (669,'PSC 2410 Photosmart');
INSERT INTO Product(id,description) VALUES (670,'PSC 2510 Photosmart');
INSERT INTO Product(id,description) VALUES (671,'Photosmart');
INSERT INTO Product(id,description) VALUES (672,'Photosmart (original)');
INSERT INTO Product(id,description) VALUES (673,'Photosmart 100');
INSERT INTO Product(id,description) VALUES (674,'Photosmart 130');
INSERT INTO Product(id,description) VALUES (675,'Photosmart 145');
INSERT INTO Product(id,description) VALUES (676,'Photosmart 230');
INSERT INTO Product(id,description) VALUES (677,'Photosmart 245');
INSERT INTO Product(id,description) VALUES (678,'Photosmart 325');
INSERT INTO Product(id,description) VALUES (679,'Photosmart 335');
INSERT INTO Product(id,description) VALUES (680,'Photosmart 375');
INSERT INTO Product(id,description) VALUES (681,'Photosmart 385');
INSERT INTO Product(id,description) VALUES (682,'Photosmart 475');
INSERT INTO Product(id,description) VALUES (683,'Photosmart 1000 / p1000');
INSERT INTO Product(id,description) VALUES (684,'Photosmart 1115');
INSERT INTO Product(id,description) VALUES (685,'Photosmart 1215');
INSERT INTO Product(id,description) VALUES (686,'Photosmart 1218');
INSERT INTO Product(id,description) VALUES (687,'Photosmart 1315');
INSERT INTO Product(id,description) VALUES (688,'Photosmart 2575');
INSERT INTO Product(id,description) VALUES (689,'Photosmart 2610');
INSERT INTO Product(id,description) VALUES (690,'Photosmart 2710');
INSERT INTO Product(id,description) VALUES (691,'Photosmart 3110');
INSERT INTO Product(id,description) VALUES (692,'Photosmart 3210');
INSERT INTO Product(id,description) VALUES (693,'Photosmart 3310');
INSERT INTO Product(id,description) VALUES (694,'Photosmart 5510 e-All-in-One Printer');
INSERT INTO Product(id,description) VALUES (695,'Photosmart 5514 e-All-in-One Printer');
INSERT INTO Product(id,description) VALUES (696,'Photosmart 5520 e-All-in-One Printer');
INSERT INTO Product(id,description) VALUES (697,'Photosmart 6510 e-All-in-One Printer');
INSERT INTO Product(id,description) VALUES (698,'Photosmart 6520 e-All-in-One Printer');
INSERT INTO Product(id,description) VALUES (699,'Photosmart 7150');
INSERT INTO Product(id,description) VALUES (700,'Photosmart 7260 (Introduced August 2007)');
INSERT INTO Product(id,description) VALUES (701,'Photosmart 7350');
INSERT INTO Product(id,description) VALUES (702,'Photosmart 7355');
INSERT INTO Product(id,description) VALUES (703,'Photosmart 7450');
INSERT INTO Product(id,description) VALUES (704,'Photosmart 7460');
INSERT INTO Product(id,description) VALUES (705,'Photosmart 7510 e-All-in-One Printer');
INSERT INTO Product(id,description) VALUES (706,'Photosmart 7520 e-All-in-One Printer');
INSERT INTO Product(id,description) VALUES (707,'Photosmart 7525 e-All-in-One Printer');
INSERT INTO Product(id,description) VALUES (708,'Photosmart 7550');
INSERT INTO Product(id,description) VALUES (709,'Photosmart 7660');
INSERT INTO Product(id,description) VALUES (710,'Photosmart 7760');
INSERT INTO Product(id,description) VALUES (711,'Photosmart 7960');
INSERT INTO Product(id,description) VALUES (712,'Photosmart 8049/8050');
INSERT INTO Product(id,description) VALUES (713,'Photosmart 8150 (Introduced in 2004)');
INSERT INTO Product(id,description) VALUES (714,'Photosmart 8450');
INSERT INTO Product(id,description) VALUES (715,'Photosmart 8750');
INSERT INTO Product(id,description) VALUES (716,'Photosmart A310');
INSERT INTO Product(id,description) VALUES (717,'Photosmart A510 series');
INSERT INTO Product(id,description) VALUES (718,'Photosmart A610 series');
INSERT INTO Product(id,description) VALUES (719,'Photosmart A710');
INSERT INTO Product(id,description) VALUES (720,'Photosmart C3180');
INSERT INTO Product(id,description) VALUES (721,'Photosmart C4180');
INSERT INTO Product(id,description) VALUES (722,'Photosmart C4280');
INSERT INTO Product(id,description) VALUES (723,'Photosmart C4380');
INSERT INTO Product(id,description) VALUES (724,'Photosmart C4480');
INSERT INTO Product(id,description) VALUES (725,'Photosmart C4580');
INSERT INTO Product(id,description) VALUES (726,'Photosmart C4680');
INSERT INTO Product(id,description) VALUES (727,'Photosmart C4780');
INSERT INTO Product(id,description) VALUES (728,'Photosmart C4795');
INSERT INTO Product(id,description) VALUES (729,'Photosmart C5180');
INSERT INTO Product(id,description) VALUES (730,'Photosmart C5280');
INSERT INTO Product(id,description) VALUES (731,'Photosmart C5380');
INSERT INTO Product(id,description) VALUES (732,'Photosmart C6180 All-in-One Printer');
INSERT INTO Product(id,description) VALUES (733,'Photosmart C6280');
INSERT INTO Product(id,description) VALUES (734,'Photosmart C7180');
INSERT INTO Product(id,description) VALUES (735,'Photosmart C7280');
INSERT INTO Product(id,description) VALUES (736,'Photosmart C7288');
INSERT INTO Product(id,description) VALUES (737,'Photosmart C8180');
INSERT INTO Product(id,description) VALUES (738,'Photosmart D7560');
INSERT INTO Product(id,description) VALUES (739,'Photosmart eStation e-All-in-One Printer – C510a');
INSERT INTO Product(id,description) VALUES (740,'Photosmart p1000');
INSERT INTO Product(id,description) VALUES (741,'Photosmart p1100 / p1100xi');
INSERT INTO Product(id,description) VALUES (742,'Photosmart Plus e-All-in-One Printer – B210a');
INSERT INTO Product(id,description) VALUES (743,'Photosmart Premium e-All-in-One Printer – C310a');
INSERT INTO Product(id,description) VALUES (744,'Photosmart Premium Fax e-All-in-One Printer – C410a');
INSERT INTO Product(id,description) VALUES (745,'Photosmart Wireless e-All-in-One Printer – B110a');
INSERT INTO Product(id,description) VALUES (746,'7210');
INSERT INTO Product(id,description) VALUES (747,'7220');
INSERT INTO Product(id,description) VALUES (748,'7230');
INSERT INTO Product(id,description) VALUES (749,'7250');
INSERT INTO Product(id,description) VALUES (750,'7270');
INSERT INTO Product(id,description) VALUES (751,'7280');
INSERT INTO Product(id,description) VALUES (752,'7290');
INSERT INTO Product(id,description) VALUES (753,'7510');
INSERT INTO Product(id,description) VALUES (754,'7520');
INSERT INTO Product(id,description) VALUES (755,'7730');
INSERT INTO Product(id,description) VALUES (756,'7750');
INSERT INTO Product(id,description) VALUES (757,'7780');
INSERT INTO Product(id,description) VALUES (758,'G-Force');
INSERT INTO Product(id,description) VALUES (759,'DC01');
INSERT INTO Product(id,description) VALUES (760,'DC03');
INSERT INTO Product(id,description) VALUES (761,'DC04');
INSERT INTO Product(id,description) VALUES (762,'DC07');
INSERT INTO Product(id,description) VALUES (763,'DC14');
INSERT INTO Product(id,description) VALUES (764,'DC15');
INSERT INTO Product(id,description) VALUES (765,'DC17');
INSERT INTO Product(id,description) VALUES (766,'DC18');
INSERT INTO Product(id,description) VALUES (767,'DC24');
INSERT INTO Product(id,description) VALUES (768,'DC25');
INSERT INTO Product(id,description) VALUES (769,'DC27');
INSERT INTO Product(id,description) VALUES (770,'DC28');
INSERT INTO Product(id,description) VALUES (771,'DC33');
INSERT INTO Product(id,description) VALUES (772,'DC40');
INSERT INTO Product(id,description) VALUES (773,'DC41');
INSERT INTO Product(id,description) VALUES (774,'DC42');
INSERT INTO Product(id,description) VALUES (775,'DC43');
INSERT INTO Product(id,description) VALUES (776,'DC50');
INSERT INTO Product(id,description) VALUES (777,'DC51');
INSERT INTO Product(id,description) VALUES (778,'DC55');
INSERT INTO Product(id,description) VALUES (779,'IBM 001');
INSERT INTO Product(id,description) VALUES (780,'IBM 003');
INSERT INTO Product(id,description) VALUES (781,'IBM 010');
INSERT INTO Product(id,description) VALUES (782,'IBM 011');
INSERT INTO Product(id,description) VALUES (783,'IBM 012');
INSERT INTO Product(id,description) VALUES (784,'IBM 013');
INSERT INTO Product(id,description) VALUES (785,'IBM 015');
INSERT INTO Product(id,description) VALUES (786,'IBM 016');
INSERT INTO Product(id,description) VALUES (787,'IBM 020');
INSERT INTO Product(id,description) VALUES (788,'IBM 024');
INSERT INTO Product(id,description) VALUES (789,'IBM 026');
INSERT INTO Product(id,description) VALUES (790,'IBM 027');
INSERT INTO Product(id,description) VALUES (791,'IBM 028');
INSERT INTO Product(id,description) VALUES (792,'IBM 029');
INSERT INTO Product(id,description) VALUES (793,'IBM 031');
INSERT INTO Product(id,description) VALUES (794,'IBM 032');
INSERT INTO Product(id,description) VALUES (795,'IBM 033');
INSERT INTO Product(id,description) VALUES (796,'IBM 034');
INSERT INTO Product(id,description) VALUES (797,'IBM 036');
INSERT INTO Product(id,description) VALUES (798,'IBM 037');
INSERT INTO Product(id,description) VALUES (799,'IBM 040');
INSERT INTO Product(id,description) VALUES (800,'IBM 041');
INSERT INTO Product(id,description) VALUES (801,'IBM 043');
INSERT INTO Product(id,description) VALUES (802,'IBM 044');
INSERT INTO Product(id,description) VALUES (803,'IBM 046');
INSERT INTO Product(id,description) VALUES (804,'IBM 047');
INSERT INTO Product(id,description) VALUES (805,'IBM 051');
INSERT INTO Product(id,description) VALUES (806,'IBM 052');
INSERT INTO Product(id,description) VALUES (807,'IBM 053');
INSERT INTO Product(id,description) VALUES (808,'IBM 054');
INSERT INTO Product(id,description) VALUES (809,'IBM 055');
INSERT INTO Product(id,description) VALUES (810,'IBM 056');
INSERT INTO Product(id,description) VALUES (811,'IBM 058');
INSERT INTO Product(id,description) VALUES (812,'IBM 059');
INSERT INTO Product(id,description) VALUES (813,'DynaTAC 8000 Series');
INSERT INTO Product(id,description) VALUES (814,'DynaTAC International Series');
INSERT INTO Product(id,description) VALUES (815,'DynaTAC 6000XL');
INSERT INTO Product(id,description) VALUES (816,'Ultra Classic');
INSERT INTO Product(id,description) VALUES (817,'Ultra Classic II');
INSERT INTO Product(id,description) VALUES (818,'International 1000/2000/2200/2700');
INSERT INTO Product(id,description) VALUES (819,'MicroTAC');
INSERT INTO Product(id,description) VALUES (820,'MicroTAC Classic');
INSERT INTO Product(id,description) VALUES (821,'MicroTAC II');
INSERT INTO Product(id,description) VALUES (822,'MicroTAC Alpha');
INSERT INTO Product(id,description) VALUES (823,'MicroTAC Lite');
INSERT INTO Product(id,description) VALUES (824,'MicroTAC Elite');
INSERT INTO Product(id,description) VALUES (825,'Bag Phone');
INSERT INTO Product(id,description) VALUES (826,'StarTAC');
INSERT INTO Product(id,description) VALUES (827,'Timeport');
INSERT INTO Product(id,description) VALUES (828,'MR30');
INSERT INTO Product(id,description) VALUES (829,'MicroTAC International Series');
INSERT INTO Product(id,description) VALUES (830,'MicroTAC DPC Series');
INSERT INTO Product(id,description) VALUES (831,'StarTAC 2004');
INSERT INTO Product(id,description) VALUES (832,'V3620');
INSERT INTO Product(id,description) VALUES (833,'A008 (Accompli 008)');
INSERT INTO Product(id,description) VALUES (834,'A388 (Accompli 388)');
INSERT INTO Product(id,description) VALUES (835,'A388C (Accompli 388)');
INSERT INTO Product(id,description) VALUES (836,'A760 – Developed and introduced in China');
INSERT INTO Product(id,description) VALUES (837,'A768');
INSERT INTO Product(id,description) VALUES (838,'A768i');
INSERT INTO Product(id,description) VALUES (839,'A853 (MILESTONE)');
INSERT INTO Product(id,description) VALUES (840,'A855 (DROID)');
INSERT INTO Product(id,description) VALUES (841,'A953 (MILESTONE 2)');
INSERT INTO Product(id,description) VALUES (842,'A955 (DROID2)');
INSERT INTO Product(id,description) VALUES (843,'A910/A910i');
INSERT INTO Product(id,description) VALUES (844,'A920');
INSERT INTO Product(id,description) VALUES (845,'A925');
INSERT INTO Product(id,description) VALUES (846,'A1000');
INSERT INTO Product(id,description) VALUES (847,'A1010');
INSERT INTO Product(id,description) VALUES (848,'A1200 (MING)');
INSERT INTO Product(id,description) VALUES (849,'A1600 (MING2)');
INSERT INTO Product(id,description) VALUES (850,'A3100 (SURF)');
INSERT INTO Product(id,description) VALUES (851,'A6288');
INSERT INTO Product(id,description) VALUES (852,'Kwanon');
INSERT INTO Product(id,description) VALUES (853,'Canon');
INSERT INTO Product(id,description) VALUES (854,'Hansa Canon');
INSERT INTO Product(id,description) VALUES (855,'Canon S');
INSERT INTO Product(id,description) VALUES (856,'Canon NS');
INSERT INTO Product(id,description) VALUES (857,'Canon J');
INSERT INTO Product(id,description) VALUES (858,'Canon J II');
INSERT INTO Product(id,description) VALUES (859,'Canon S');
INSERT INTO Product(id,description) VALUES (860,'Canon S II');
INSERT INTO Product(id,description) VALUES (861,'Canon II B');
INSERT INTO Product(id,description) VALUES (862,'Canon II C');
INSERT INTO Product(id,description) VALUES (863,'Canon III');
INSERT INTO Product(id,description) VALUES (864,'Canon IV');
INSERT INTO Product(id,description) VALUES (865,'Canon III A');
INSERT INTO Product(id,description) VALUES (866,'Canon IV S');
INSERT INTO Product(id,description) VALUES (867,'Canon II A');
INSERT INTO Product(id,description) VALUES (868,'Canon II D');
INSERT INTO Product(id,description) VALUES (869,'Canon IV SB');
INSERT INTO Product(id,description) VALUES (870,'Canon II AF');
INSERT INTO Product(id,description) VALUES (871,'Canon II F');
INSERT INTO Product(id,description) VALUES (872,'Canon II AX');
INSERT INTO Product(id,description) VALUES (873,'Canon II S');
INSERT INTO Product(id,description) VALUES (874,'Canon IV Sb2');
INSERT INTO Product(id,description) VALUES (875,'Canon II S2');
INSERT INTO Product(id,description) VALUES (876,'Canon II D2');
INSERT INTO Product(id,description) VALUES (877,'Canon II F2');
